//
// Created by rossk on 23/01/2023.
//

#ifndef OBJECT_ORIENTATED_PROJECT2023_LINKED_PAGE_HPP
#define OBJECT_ORIENTATED_PROJECT2023_LINKED_PAGE_HPP


class Linked_Page {

};


#endif //OBJECT_ORIENTATED_PROJECT2023_LINKED_PAGE_HPP
